package subscription

import (
	"crypto/sha256"
	"crypto/x509"
	"encoding/hex"
	"encoding/pem"
	"errors"
	"fmt"
	"net"
	"net/netip"
	"net/url"
	"strconv"
	"strings"
	"unicode"
	"xingdu.app/xingdu/internal/protocol"
)

// CompatibilityError is deliberately free of credentials, addresses and names.
type CompatibilityError struct{ Format, Protocol, Reason string }

func (e *CompatibilityError) Error() string { return e.Reason }

func ValidFormat(format string) bool {
	switch format {
	case "stash", "mihomo", "surge", "loon", "hysteria2_uri":
		return true
	}
	return false
}
func Supports(format, kind string) bool {
	switch kind {
	case "wireguard":
		return format == "stash" || format == "mihomo"
	case "trusttunnel":
		return format == "stash"
	case "socks", "mixed":
		return format == "stash" || format == "mihomo" || format == "surge"
	case "hysteria", "shadowtls":
		return format == "stash" || format == "mihomo"
	case "snell":
		return format == "stash" || format == "surge"
	case "snell6":
		return format == "surge"
	}
	if kind == "anytls" || kind == "http" {
		return format == "stash" || format == "mihomo"
	}
	if protocol.IsShadowsocks(kind) {
		return format == "stash" || format == "mihomo" || format == "surge"
	}
	switch format {
	case "stash", "mihomo":
		return kind == "trojan" || kind == "vless" || kind == "vmess" || kind == "hysteria2" || kind == "tuic"
	case "surge":
		return kind == "trojan" || kind == "vmess" || kind == "hysteria2" || kind == "tuic"
	case "loon":
		return kind == "trojan" || kind == "vless" || kind == "vmess" || kind == "hysteria2"
	case "hysteria2_uri":
		return kind == "hysteria2"
	}
	return false
}

// INI labels exclude delimiters instead of assuming undocumented quote escaping.
// Collisions after sanitizing are resolved by nodeLabels.
func iniLabel(n Node) string {
	name := strings.Map(func(r rune) rune {
		if unicode.IsLetter(r) || unicode.IsNumber(r) || r == ' ' || r == '-' || r == '_' || r == '.' {
			return r
		}
		return '-'
	}, n.Name)
	return strings.TrimSpace(name)
}
func certificatePin(n Node) string {
	block, _ := pem.Decode([]byte(n.Spec.Certificate))
	sum := sha256.Sum256(block.Bytes)
	return hex.EncodeToString(sum[:])
}

// Loon's official grammar does not document leaf pinning. This adapter is
// explicitly PKI-only: reject self-signed/private-CA chains rather than adding
// a guessed parameter or disabling certificate checks. No AIA network fetches.
func verifyPublicCertificate(n Node) error {
	rest := []byte(n.Spec.Certificate)
	block, rest := pem.Decode(rest)
	if block == nil {
		return errors.New("invalid certificate")
	}
	leaf, err := x509.ParseCertificate(block.Bytes)
	if err != nil {
		return err
	}
	intermediates := x509.NewCertPool()
	for len(rest) > 0 {
		var b *pem.Block
		b, rest = pem.Decode(rest)
		if b == nil {
			break
		}
		if b.Type == "CERTIFICATE" {
			cert, e := x509.ParseCertificate(b.Bytes)
			if e != nil {
				return e
			}
			intermediates.AddCert(cert)
		}
	}
	_, err = leaf.Verify(x509.VerifyOptions{DNSName: n.Spec.ServerName, Intermediates: intermediates})
	return err
}

func renderOther(format, name string, nodes []Node, rules []Rule, final string) ([]byte, error) {
	// Reuse the established strict boundary before translating any grammar.
	if err := validateExport(name, nodes, rules, final); err != nil {
		return nil, err
	}
	for _, n := range nodes {
		if n.Spec.V2Ray != nil || n.Spec.QUIC != nil || n.Spec.WireGuard != nil || n.Spec.UDPEnabled {
			return nil, &CompatibilityError{format, n.Spec.Protocol, "此客户端导出尚未支持自定义传输配置"}
		}
		if !Supports(format, n.Spec.Protocol) {
			return nil, &CompatibilityError{format, n.Spec.Protocol, "所选客户端格式不支持订阅中的协议，请调整节点选择或客户端格式"}
		}
		if format == "loon" && verifyPublicCertificate(n) != nil {
			return nil, &CompatibilityError{format, n.Spec.Protocol, "Loon 格式要求系统信任的完整证书链；不能导出自签名或私有 CA 证书"}
		}
	}
	if format == "hysteria2_uri" {
		if len(rules) > 0 || final != "proxy" {
			return nil, &CompatibilityError{format, "", "分享链接不包含分流规则；请清空规则并将默认连接设为使用节点"}
		}
		var out strings.Builder
		names := nodeLabels(nodes, false)
		for i, n := range nodes {
			q := url.Values{"sni": {n.Spec.ServerName}, "insecure": {"0"}, "pinSHA256": {certificatePin(n)}}
			u := url.URL{Scheme: "hysteria2", User: url.User(n.Spec.Credential), Host: net.JoinHostPort(n.Server, strconv.Itoa(n.Spec.Port)), Path: "/", RawQuery: q.Encode(), Fragment: names[i]}
			out.WriteString(u.String() + "\n")
		}
		return []byte(out.String()), nil
	}
	var out strings.Builder
	out.WriteString("# Generated by Xingdu. Credentials are private.\n[Proxy]\n")
	labels := nodeLabels(nodes, true)
	for i, n := range nodes {
		s := n.Spec
		label := labels[i]
		if protocol.IsShadowsocks(s.Protocol) {
			fmt.Fprintf(&out, "%s = ss, %s, %d, encrypt-method=%s, password=%s, udp-relay=false\n", label, n.Server, s.Port, protocol.Cipher(s.Protocol), s.Credential)
			continue
		}
		if s.Protocol == "socks" || s.Protocol == "mixed" {
			fmt.Fprintf(&out, "%s = socks5, %s, %d, username=xingdu, password=%s, udp-relay=false\n", label, n.Server, s.Port, s.Credential)
			continue
		}
		if s.Protocol == "snell" || s.Protocol == "snell6" {
			fmt.Fprintf(&out, "%s = snell, %s, %d, psk=%s, version=%d, udp-relay=false\n", label, n.Server, s.Port, s.Credential, protocol.SnellClientVersion(s.Protocol))
			continue
		}
		kind := s.Protocol
		if format == "surge" && kind == "tuic" {
			kind = "tuic-v5"
		}
		fmt.Fprintf(&out, "%s = %s, %s, %d", label, kind, n.Server, s.Port)
		if format == "surge" {
			switch s.Protocol {
			case "trojan", "hysteria2":
				fmt.Fprintf(&out, ", password=%s", s.Credential)
			case "vmess":
				fmt.Fprintf(&out, ", username=%s, vmess-aead=true, encrypt-method=aes-128-gcm, tls=true", s.Credential)
			case "tuic":
				fmt.Fprintf(&out, ", uuid=%s, password=%s", s.Credential, s.Password)
			}
			fmt.Fprintf(&out, ", sni=%s, skip-cert-verify=false, server-cert-fingerprint-sha256=%s", s.ServerName, certificatePin(n))
		} else {
			if s.Protocol == "vmess" {
				out.WriteString(", aes-128-gcm")
			}
			fmt.Fprintf(&out, ", %q", s.Credential)
			if s.Protocol == "vmess" {
				out.WriteString(", alterId=0")
			}
			if s.Protocol == "vmess" || s.Protocol == "vless" {
				out.WriteString(", transport=tcp, over-tls=true")
			}
			fmt.Fprintf(&out, ", tls-name=%s, skip-cert-verify=false, udp=true", s.ServerName)
		}
		out.WriteByte('\n')
	}
	out.WriteString("\n[Proxy Group]\nXingdu = select, " + strings.Join(labels, ", ") + "\n\n[Rule]\n")
	for _, r := range rules {
		kind, value := "DOMAIN", strings.ToLower(r.Value)
		if r.Type == "domain_suffix" {
			kind = "DOMAIN-SUFFIX"
		}
		if r.Type == "ip_cidr" {
			prefix, _ := netip.ParsePrefix(r.Value)
			value = prefix.Masked().String()
			kind = "IP-CIDR"
			if prefix.Addr().Is6() {
				kind = "IP-CIDR6"
			}
		}
		fmt.Fprintf(&out, "%s,%s,%s\n", kind, value, policy(r.Target))
	}
	fmt.Fprintf(&out, "FINAL,%s\n", policy(final))
	return []byte(out.String()), nil
}
